"""Frozen tests (TRO-144) — CON5 mutation provenance in the console runner.

FROZEN CONTRACT: the coding agent implements, in `agentforge/web/runner.py`:
  (1) an injectable per-attempt seam — `run_campaign(..., run_one=None)` — that
      falls back to the module-global `_run_one` at CALL TIME when not supplied,
      so the existing `tests/test_web_console_ux.py` (which does
      `monkeypatch.setattr(runner, "_run_one", ...)`) STAYS GREEN; and
  (2) a mutation loop: when a base probe comes back a PARTIAL success (a near-miss
      worth mutating), spawn ONE follow-up 'mutation' attempt whose `mutation_of`
      points at the parent attempt's `seq`. A clean fail spawns no mutation.

Do NOT edit this file.
"""

from __future__ import annotations

import asyncio

from agentforge.web.runner import STATE, run_campaign


def _attempt(seq: int, verdict: str) -> dict:
    sev = {"partial": "medium", "success": "high"}.get(verdict, "low")
    return {
        "seq": seq,
        "attack_id": f"a{seq}",
        "category": "prompt_injection",
        "subcategory": "direct-override",
        "owasp": "LLM01:2025-prompt-injection",
        "route": "/api/copilot/turn",
        "http_status": 200,
        "verdict": verdict,
        "severity": sev,
        "predicate": None,
        "cost_usd": 0.0,
        "agent_path": ["orchestrator", "red_team", "target", "judge"],
        "trace": [],
        "repro": {"route": "/api/copilot/turn", "payload": {}},
        "turns": 1,
        "mutation_of": None,
        "ts": "2026-07-23T00:00:00Z",
    }


def _drive(fake, **kw) -> list[dict]:
    async def go():
        return [e async for e in run_campaign("tok", run_one=fake, **kw)]

    return asyncio.run(go())


def test_partial_base_probe_spawns_a_mutation_with_provenance() -> None:
    calls = {"n": 0}

    def fake(token, spec, seq):
        calls["n"] += 1
        # base AND mutation both return partial: a correct impl mutates the base
        # exactly ONCE and must NOT recurse on the mutation's own partial verdict.
        return _attempt(seq, "partial")

    STATE.stop = False
    events = _drive(fake, categories=["prompt_injection"])
    attempts = [e["data"] for e in events if e["event"] == "attempt"]

    base = [a for a in attempts if a.get("mutation_of") is None]
    muts = [a for a in attempts if a.get("mutation_of") is not None]
    assert len(base) == 1
    assert len(muts) == 1, "exactly one mutation — the mutation's own partial must not recurse"
    assert muts[0]["mutation_of"] == base[0]["seq"]
    assert muts[0]["seq"] != base[0]["seq"]  # the mutation gets a FRESH seq, not the base's


def test_no_mutation_when_base_probe_is_a_clean_fail() -> None:
    def fake(token, spec, seq):
        return _attempt(seq, "fail")

    STATE.stop = False
    events = _drive(fake, categories=["prompt_injection"])
    attempts = [e["data"] for e in events if e["event"] == "attempt"]
    assert attempts  # the base attempt streamed
    assert all(a.get("mutation_of") is None for a in attempts)
