"""Frozen tests (TRO-146) — the console consults the REAL deterministic Orchestrator
for the next-target + cost-without-signal halt, instead of re-implementing a fixed
coverage sweep in ``web/runner.py``.

FROZEN CONTRACT: implement ``orchestrator_verdict`` in ``agentforge/web/runner.py`` — it
must build an in-memory store reflecting the per-category coverage and DELEGATE to
``agentforge.orchestrator.Orchestrator`` (``next_directive`` for the least-covered target,
``should_halt`` for the cost-without-signal halt). Do NOT edit this file, and keep the
existing ``tests/test_web_console_ux.py`` green.

Returns a dict: ``{"next_category": str, "next_reason": str, "halt": str | None}``.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from agentforge.contracts.common import AttackCategory
from agentforge.contracts.verdict import Outcome, Severity
from agentforge.orchestrator import Orchestrator
from agentforge.store import ExploitRecord
from agentforge.web.runner import CATEGORIES, orchestrator_verdict

_FIXED = datetime(2026, 7, 20, 12, 0, 0, tzinfo=timezone.utc)


def test_halt_matches_orchestrator_should_halt() -> None:
    # over budget with NO breach -> cost-without-signal halt
    over = orchestrator_verdict({"prompt_injection": 1}, spent_usd=5.0, budget_usd=5.0, breaches=0)
    assert over["halt"] is not None
    assert "cost" in over["halt"].lower() or "budget" in over["halt"].lower()
    # a confirmed breach IS signal -> no halt even at/over budget
    signal = orchestrator_verdict({"prompt_injection": 1}, spent_usd=5.0, budget_usd=5.0, breaches=2)
    assert signal["halt"] is None
    # under budget -> no halt
    under = orchestrator_verdict({"prompt_injection": 1}, spent_usd=1.0, budget_usd=5.0, breaches=0)
    assert under["halt"] is None


def test_next_target_is_not_a_heavily_probed_category() -> None:
    v = orchestrator_verdict({"prompt_injection": 9}, spent_usd=0.1, budget_usd=5.0, breaches=0)
    assert v["next_category"] != "prompt_injection"  # least-covered wins, not the probed one
    assert v["next_reason"]  # a non-empty, human-readable why-next
    assert v["next_category"] in CATEGORIES  # a category the console can actually probe


class _Store:
    """Minimal in-memory ExploitStore for the parity check."""

    def __init__(self, records: list[ExploitRecord]) -> None:
        self._r = records

    def record(self, rec: ExploitRecord) -> bool:
        self._r.append(rec)
        return True

    def all(self) -> list[ExploitRecord]:
        return list(self._r)

    def cases_tested_by_category(self) -> dict[AttackCategory, int]:
        d: dict[AttackCategory, int] = {}
        for r in self._r:
            d[r.attack_category] = d.get(r.attack_category, 0) + 1
        return d

    def open_findings_by_category(self) -> dict[AttackCategory, int]:
        return {}

    def regressions(self) -> list[ExploitRecord]:
        return []


def test_next_target_has_parity_with_the_real_orchestrator() -> None:
    # whatever the console helper reports as next_category MUST equal what the real
    # deterministic Orchestrator.next_directive picks for the same coverage — no drift.
    coverage = {"prompt_injection": 3, "data_exfiltration": 1, "tool_misuse": 2}
    recs: list[ExploitRecord] = []
    i = 0
    for cat, n in coverage.items():
        for _ in range(n):
            i += 1
            recs.append(
                ExploitRecord(
                    exploit_id=f"e{i}",
                    correlation_id="c",
                    attack_id=str(uuid.uuid4()),
                    sequence_hash=f"h{i}",
                    attack_category=AttackCategory(cat),
                    severity=Severity.LOW,
                    outcome=Outcome.FAIL,
                    adjudicated_at=_FIXED,
                )
            )
    expected = (
        Orchestrator(_Store(recs))
        .next_directive(
            correlation_id="c",
            authorized_patient_uuid="p",
            target_base_url=None,
            max_usd=5.0,
            max_attempts=10,
        )
        .attack_category.value
    )

    v = orchestrator_verdict(coverage, spent_usd=0.1, budget_usd=5.0, breaches=0)
    assert v["next_category"] == expected
